services:
  db:
    container_name: db
    networks:
      - my-network-name
    image: mysql
    volumes:
      - type: volume
        source: mySqlData
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: RECOMMENDATION
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  web:
    networks:
      - my-network-name
    build: .
    restart: always
    image: springbootdemo_web
    ports:
      - 3333:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      db:
        condition: service_healthy

networks:
  my-network-name:
    name: my-global-net
volumes:
  mySqlData: